version: 2
jobs:
   build:
     docker:
       - image: circleci/node:10.7.0
     steps:
       - add_ssh_keys:
          fingerprints:
            - "66:2b:78:fe:40:56:af:39:c1:81:ef:09:7d:ef:68:18"
       - checkout
       - run: npm install yarn && yarn
       - run: yarn run test
       - deploy:
          name: deploy to princesspoopan.com
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run build && ./scripts/deployment.sh
            fi
