version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7.10.0
     steps:
       - checkout
       - run: npm install yarn && yarn
       - run: yarn run test
       - run: echo "princesspoopan.com is built"
